import { db } from './db.mjs';
import { createHash } from 'node:crypto';
import { ensureEmailTable, sendOrderEmails } from './order-emails.mjs';
import { creditOrderPoints, ensureLoyalty, hash as loyaltyHash, norm } from './loyalty.mjs';
const reply=(x,s=200)=>Response.json(x,{status:s}); const cents=n=>Math.round(Number(n)*100); const giftHash=s=>createHash('sha256').update(String(s).trim().toUpperCase()).digest('hex');
const REWARDS=new Map([[100,500],[200,1200],[300,2000],[500,4000]]);
async function catalogue(req){const origin=process.env.URL||new URL(req.url).origin,r=await fetch(`${origin}/assets/products.json`);if(!r.ok)throw Error('Catalogue inaccessible.');const d=await r.json();return Array.isArray(d)?d:d.products||[]}
const keys=p=>[p.id,p.slug,p.sku,p.name,p.title].filter(Boolean).map(String), price=p=>Number(p.price??p.prix??p.unitPrice??p.unit_price);
async function releaseGift(sql,orderId){const r=await sql`SELECT * FROM gift_card_redemptions WHERE order_id=${orderId} AND status='reserved' LIMIT 1`;if(r[0]){await sql`UPDATE gift_cards SET balance_cents=balance_cents+${r[0].amount_cents},status='active',updated_at=NOW() WHERE id=${r[0].gift_card_id}`;await sql`UPDATE gift_card_redemptions SET status='released',updated_at=NOW() WHERE id=${r[0].id}`;}}
async function applyGift(sql,orderId,ref){const r=await sql`UPDATE gift_card_redemptions SET status='applied',updated_at=NOW() WHERE order_id=${orderId} AND status='reserved' RETURNING *`;if(r[0])await sql`INSERT INTO gift_card_ledger(gift_card_id,event_type,amount_cents,order_ref,note) VALUES(${r[0].gift_card_id},'redeemed',${-r[0].amount_cents},${ref},'Utilisation commande en ligne')`;}
async function releaseLoyalty(sql,orderId){const r=await sql`UPDATE loyalty_redemptions SET status='released',updated_at=NOW() WHERE order_id=${orderId} AND status='reserved' RETURNING *`;if(r[0])await sql`UPDATE loyalty_accounts SET points=points+${r[0].points},updated_at=NOW() WHERE id=${r[0].account_id}`;}
async function applyLoyalty(sql,orderId,ref){const r=await sql`UPDATE loyalty_redemptions SET status='applied',updated_at=NOW() WHERE order_id=${orderId} AND status='reserved' RETURNING *`;if(r[0])await sql`INSERT INTO loyalty_ledger(account_id,event_type,points,order_id,order_ref,note) VALUES(${r[0].account_id},'reward_redeemed',${-r[0].points},${orderId},${ref},${`Récompense fidélité ${(r[0].discount_cents/100).toFixed(0)} €`})`;}
async function reserveLoyalty(sql,o,orderId,total){const points=Number(o.loyalty_reward_points||0);if(!points)return {points:0,discount:0,accountId:null};const discount=REWARDS.get(points);if(!discount)throw Object.assign(Error('Récompense fidélité invalide.'),{status:400});if(total<discount)throw Object.assign(Error(`Cette récompense nécessite une commande d’au moins ${(discount/100).toFixed(2).replace('.',',')} €.`),{status:400});const token=String(o.loyalty_token||'');if(!token)throw Object.assign(Error('Reconnectez-vous à votre compte fidélité.'),{status:401});await ensureLoyalty(sql);const session=(await sql`SELECT s.account_id,a.email FROM loyalty_sessions s JOIN loyalty_accounts a ON a.id=s.account_id WHERE s.token_hash=${loyaltyHash(token)} AND s.expires_at>NOW() LIMIT 1`)[0];if(!session)throw Object.assign(Error('Session fidélité expirée. Reconnectez-vous.'),{status:401});const customerEmail=norm(o.customer?.email||o.email);if(!customerEmail||customerEmail!==norm(session.email))throw Object.assign(Error('Utilisez la même adresse email que votre compte fidélité.'),{status:400});const upd=await sql`UPDATE loyalty_accounts SET points=points-${points},updated_at=NOW() WHERE id=${session.account_id} AND points>=${points} RETURNING id`;if(!upd[0])throw Object.assign(Error('Vous n’avez plus assez de points pour cette récompense.'),{status:409});await sql`INSERT INTO loyalty_redemptions(order_id,account_id,points,discount_cents) VALUES(${orderId},${session.account_id},${points},${discount})`;await sql`UPDATE orders SET loyalty_account_id=${session.account_id},loyalty_points_used=${points},loyalty_discount_cents=${discount} WHERE id=${orderId}`;return {points,discount,accountId:session.account_id};}
export default async(req)=>{if(req.method!=='POST')return reply({error:'Méthode non autorisée.'},405);let b;try{b=await req.json()}catch{return reply({error:'Requête invalide.'},400)}const o=b.order;if(!o||!Array.isArray(o.items)||!o.items.length)return reply({error:'Panier vide.'},400);const sql=db();
 let products;try{products=await catalogue(req)}catch(e){return reply({error:e.message},500)}const map=new Map();for(const p of products)for(const k of keys(p))map.set(k,p);let sub=0,items=[];for(const i of o.items){const k=String(i.id??i.slug??i.sku??i.name??i.title??''),p=map.get(k);if(!p)return reply({error:`Produit non reconnu : ${k||'sans identifiant'}`},400);const q=Math.max(1,Math.min(99,parseInt(i.qty??i.quantity??1)||1)),pc=cents(price(p));sub+=pc*q;items.push({key:k,name:p.name??p.title??k,q,pc,line:pc*q})}
 const mode=String(o.mode||'pickup');let delivery=0;if(mode==='delivery'){const zone=String(o.zone||''),fees={'aulnay':350,'10km':500,'10-15km':750,'Aulnay':350,'Jusqu’à 10 km':500,'10 à 15 km':750,'3.5':350,'5':500,'7.5':750};if(!(zone in fees))return reply({error:'Zone de livraison invalide.'},400);if(sub<2000)return reply({error:'Minimum de commande pour livraison : 20 €.'},400);delivery=fees[zone]}
 const total=sub+delivery,ref=`ADG-${Date.now()}`;let row;try{const c=o.customer||{};[row]=await sql`INSERT INTO orders(order_ref,status,mode,zone,service_date,service_slot,customer_name,customer_phone,customer_email,customer_address,comments,allergies,subtotal_cents,delivery_cents,total_cents,mollie_due_cents) VALUES(${ref},'pending_payment',${mode},${o.zone||null},${o.date||null},${o.slot||null},${c.name||o.name||null},${c.phone||o.phone||null},${c.email||o.email||null},${c.address||o.address||null},${o.comments||null},${o.allergies||null},${sub},${delivery},${total},${total}) RETURNING id`;for(const x of items)await sql`INSERT INTO order_items(order_id,product_key,product_name,quantity,unit_price_cents,line_total_cents) VALUES(${row.id},${x.key},${x.name},${x.q},${x.pc},${x.line})`;}catch(e){console.error(e);return reply({error:'Impossible d’enregistrer la commande.'},500)}
 let loyalty={points:0,discount:0};try{loyalty=await reserveLoyalty(sql,o,row.id,total)}catch(e){await sql`UPDATE orders SET status='loyalty_invalid' WHERE id=${row.id}`;return reply({error:e.message},e.status||500)}
 let gift=0;const code=String(o.gift_code||'').trim().toUpperCase();const afterLoyalty=total-loyalty.discount;if(code){const card=(await sql`SELECT id,balance_cents,status FROM gift_cards WHERE code_hash=${giftHash(code)} LIMIT 1`)[0];if(!card||card.status!=='active'||card.balance_cents<=0){await releaseLoyalty(sql,row.id);await sql`UPDATE orders SET status='gift_invalid' WHERE id=${row.id}`;return reply({error:'Carte cadeau invalide ou sans solde.'},400)}gift=Math.min(afterLoyalty,card.balance_cents);const updated=await sql`UPDATE gift_cards SET balance_cents=balance_cents-${gift},status=CASE WHEN balance_cents-${gift}=0 THEN 'depleted' ELSE status END,updated_at=NOW() WHERE id=${card.id} AND balance_cents>=${gift} RETURNING id`;if(!updated[0]){await releaseLoyalty(sql,row.id);return reply({error:'Le solde de cette carte vient de changer. Réessayez.'},409)}await sql`INSERT INTO gift_card_redemptions(order_id,gift_card_id,amount_cents) VALUES(${row.id},${card.id},${gift})`;await sql`UPDATE orders SET gift_card_id=${card.id},gift_card_cents=${gift} WHERE id=${row.id}`;}
 const due=afterLoyalty-gift;await sql`UPDATE orders SET mollie_due_cents=${due} WHERE id=${row.id}`;const site=process.env.URL||new URL(req.url).origin;if(due===0){await sql`UPDATE orders SET status='paid',paid_at=NOW() WHERE id=${row.id}`;await applyGift(sql,row.id,ref);await applyLoyalty(sql,row.id,ref);const full=(await sql`SELECT * FROM orders WHERE id=${row.id}`)[0];try{await ensureEmailTable(sql);await sendOrderEmails(sql,full)}catch(e){console.error(e)} try{await creditOrderPoints(sql,full)}catch(e){console.error('Fidélité:',e)}return reply({redirectUrl:`${site}/paiement-retour.html?ref=${encodeURIComponent(ref)}`,orderRef:ref,giftAppliedCents:gift,loyaltyDiscountCents:loyalty.discount,paidWithoutMollie:true});}
 if(!process.env.MOLLIE_API_KEY){await releaseGift(sql,row.id);await releaseLoyalty(sql,row.id);return reply({error:'Clé Mollie absente.'},500)}const payload={amount:{currency:'EUR',value:(due/100).toFixed(2)},description:`L'Atelier du Goût - ${ref}`,redirectUrl:`${site}/paiement-retour.html?ref=${encodeURIComponent(ref)}`,webhookUrl:`${site}/.netlify/functions/mollie-webhook`,locale:'fr_FR',metadata:{orderRef:ref,orderId:String(row.id),mode}};const r=await fetch('https://api.mollie.com/v2/payments',{method:'POST',headers:{Authorization:`Bearer ${process.env.MOLLIE_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),p=await r.json();if(!r.ok){await releaseGift(sql,row.id);await releaseLoyalty(sql,row.id);await sql`UPDATE orders SET status='payment_creation_failed' WHERE id=${row.id}`;return reply({error:'Mollie a refusé la création du paiement.'},502)}await sql`UPDATE orders SET mollie_payment_id=${p.id} WHERE id=${row.id}`;await sql`INSERT INTO payments(order_id,provider_payment_id,status,amount_cents) VALUES(${row.id},${p.id},${p.status||'open'},${due})`;return reply({checkoutUrl:p?._links?.checkout?.href,paymentId:p.id,orderRef:ref,giftAppliedCents:gift,loyaltyDiscountCents:loyalty.discount,mollieDueCents:due});};
